### ISSUE TITLE
Type declarations not recognized by typescript

### ISSUE THREAD

**Issue by innermatrix** [imjuni/jin-axios-curlize#9]
My TypeScript is not finding type declarations in `jin-axios-curlize` because `package.json` paths to `typings` are wrong:

`package.json` says `"typings": "./dist/esm/index.d.mts",`, but package contains only `esm/index.mjs`.

**Comment by imjuni** [comment]
@innermatrix Hi,

Thanks for the feedback to make jin-axios-curlize even better!

This happened while trying to improve the type bundling process. There was actually a missing type file, which was fixed in version 1.3.0, #10
